name: Deploy Frontend

on:
  push:
    branches: ["main"]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Frontend EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.FRONTEND_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/grocery-list-frontend
            git pull origin main
            # Set the API URL without the /api/v1/groceryItems/ path (this will be handled by the frontend)
            echo "VITE_APP_API_BASE_URL=http://ec2-3-99-216-136.ca-central-1.compute.amazonaws.com:8080" > .env
            cd docker
            sudo docker-compose down
            # Pass the environment variable through docker-compose
            sudo VITE_APP_API_BASE_URL=http://ec2-3-99-216-136.ca-central-1.compute.amazonaws.com:8080 docker-compose up -d --build
