name: Deploy Frontend

on:
  push:
    branches: ["main"]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Frontend EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.FRONTEND_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/grocery-list-frontend
            git pull origin main
            touch .env
            echo "VITE_APP_API_BASE_URL=${{ secrets.VITE_APP_API_BASE_URL }}" >> .env
            cd docker/
            sudo docker-compose down
            sudo VITE_APP_API_BASE_URL=${{ secrets.VITE_APP_API_BASE_URL }} docker-compose up -d --build
            sudo docker-compose up -d
